// react-todo-2/src/App.jsx
import { useState } from "react";
import { TodoList } from "./TodoList";
import reactLogo from "./assets/react.svg";
import "./App.css";

function App() {
  const [todo, setTodo] = useState("");
  const [todoList, settodoList] = useState([1, 2, 3]);
  
  const addTodo = () => {
    settodoList([...todoList, todo]);
    setTodo("");
  };

  return (
    <div className="App">
      <div>
        <a href="https://reactjs.org" target="_blank">
          <img src={reactLogo} className="logo react" alt="React logo" />
        </a>
      </div>
      <h1>React To do App</h1>
      <div className="card">
        <input
          type="text"
          value={todo}
          onChange={(e) => setTodo(e.target.value)}
          onKeyUp={(e) => { e.key === 'Enter' && addTodo() }}
        />

        <button onClick={addTodo}>Add to do</button>

        <TodoList todoList={todoList} msg="HELLO!"/>

      </div>
    </div>
  );
}

export default App;

// vue-todo-2/src/App.vue
<script setup>
import ToDoList from './components/ToDoList.vue'
</script>

<template>
  <div>
    <a href="https://vuejs.org/" target="_blank">
      <img src="./assets/vue.svg" class="logo vue" alt="Vue logo" />
    </a>
  </div>
  <ToDoList title="todo App in Vue" />
</template>

<style scoped>
.logo {
  height: 6em;
  padding: 1.5em;
  will-change: filter;
}
.logo:hover {
  filter: drop-shadow(0 0 2em #646cffaa);
}
.logo.vue:hover {
  filter: drop-shadow(0 0 2em #42b883aa);
}
</style>
